source 'https://rubygems.org'

# PostgreSQL driver
gem 'pg'

gem 'rspec'
gem 'faker'

# Sinatra driver
gem 'sinatra'
gem 'sinatra-contrib'

# Use Thin for our web server
gem 'thin'

gem 'activesupport'
gem 'activerecord'

gem 'eventmachine', '~> 1.0.6'

gem 'rake'

gem 'shotgun'

gem 'json'

gem 'httparty', '~> 0.13.3'

group :test do
  gem 'shoulda-matchers'
  gem 'rack-test'
end

group :test, :development do
  gem 'rspec'
  gem 'factory_girl'
  gem 'faker'
end
