# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b66c540fbe6beab660be99f331b7731dabb9fff8f91279b02deee2b7d5541eb879df48c2d43b81c549308d0fd3e365a29b1136061d7d299142a7aac7a2f43326

test:
  secret_key_base: ca5cba436776c38778a2d4207f03c42f07d12dcf16e40ef7317966c0639b95d8d2c20cfe74d965866c6df50d12ae35c4760003a575b08854b89d5d715223ec65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
